### ISSUE TITLE
File name discrepancy

### ISSUE THREAD

**Issue by kaitlynflynn** [LambdaSchool/Sprint-Challenge--Data-Structures-Algorithms#58]
Sorry - the perfectionist in me thought I'd let you know :)

1. Repo Instructions reference `Data_Structures_Answers.md` file, but it's actually labeled as `Data_Structures_Questions.md`. It also mentions an Answers.md file, but I'm not seeing anything labeled that. See below for current repo instruction: 

Repo Instruction: 
> Task 3. Analyze some runtimes
> Open up the Data_Structures_Answers.md file. This is where you'll jot down your answers for the runtimes of the functions you just implemented. Be sure to also answer any other questions posed in the Answers.md file!

**Comment by seanchen1991** [comment]
File naming has been fixed :)
